<?php

echo "<pre>";
// print_r($data);
// die;
if (isset($data)) {

    // $updatetime = $data->location->tz_id;
    // $localtime = $data->location->localtime;
    $country = $data->location->region;
    $city = $data->location->name;
    $co =$data->current->air_quality->co;
    $no2 =$data->current->air_quality->no2;
    $o3 =$data->current->air_quality->o3;
    $so2 =$data->current->air_quality->so2;




} else {

    $updatetime = "not found";
    $tempcel  = "not found";
    $country  = "not found";
    $city     = "not found";
    $wind     = "not found";
    $pressure = "not found";
    $humidity = "not found";
    $uvindex  = "not found";
}
// print_r($data);
// foreach ($data as $Key => $value) {

// }

echo "</pre>";
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather Info</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="../../../public/style.css">
</head>

<body>
    <div class="h1 text-center text-danger" style="font-family: sans-serif;">Air Quality</div>

    <div class="mt-5"></div>

    <div class="courses-container d-flex justify-content-center">
        <div class="course">
            <div class="course-preview">
                <div class="h5">Location</div>
                <h2><?php echo $city ?></h2>
                <div class="text-danger mt-2 h6"><?php echo $country ?></div>
            
            </div>
            <div class="course-info">
                <div class="progress-container">
                    <div class="progress"></div>
                    <span class="progress-text">
                        6/9 Challenges
                    </span>
                </div>
                <h6 class="text-danger"><b>CO</b></h6>
                <h6 class="text-success"><?php echo $co ?></h6>
                <h6 class="text-danger"><b>NO2</b></h6>
                <h6 class="text-success"><?php echo $no2 ?></h6>
                <h6 class="text-danger"><b>O3</b></h6>
                <h6 class="text-success"><?php echo $o3 ?></h6>
                <h6 class="text-danger"><b>SO2</b></h6>
                <h6 class="text-success"><?php echo $so2 ?></h6>
                <button class="btnn"><a style="text-decoration:none; color:white" target='_blank' href="http://localhost:8080/weather/home">Home</a></button>
            </div>
        </div>
    </div>
    <?php require_once(APP_PATH."/views/weather/button.phtml")?>

</body>

</html>