<?php

// echo "<pre>";
// print_r($data->forecast->forecastday[0]->date);
// die;

$htm = "";
if (isset($data)) {


    foreach ($data->forecast->forecastday[0]->hour as $key => $value) {
        // print_r($data->forecast->forecastday[0]->date);
        $htm .= '
        <div class="card ml-5 " style="width: 18rem;">
            <div class="card-body mt-2" style="">
                <h4 class="card-title text-danger">Location :' . $data->location->name . '</h4>
                <h5 class="card-title text-primary">Time :' . $value->time . '</h5>
                <p class="card-text text-danger mt-4">Temp ' . $value->temp_c . '°C</p>
                <p class="card-text text-success">  Wind Speed:  ' . $value->wind_kph . '</p>
                <p class="card-text text-success">  Humidity:  ' . $value->humidity . '</p>
                <p class="card-text text-success"> Heatindex:  ' . $value->heatindex_c . '</p>



                
        </div>
    </div><br>';
    }
    // $updatetime = $data->location->localtime;
    // $tempcel = $data->current->temp_c;
    // $country = $data->location->country;
    $city = $data->location->name;
    // $wind = $data->current->wind_kph;
    // $pressure = $data->current->pressure_mb;
    // $humidity = $data->current->humidity;
    // $uvindex = $data->current->uv;
} else {

    $updatetime = "not found";
    $tempcel  = "not found";
    $country  = "not found";
    $city     = "not found";
    $wind     = "not found";
    $pressure = "not found";
    $humidity = "not found";
    $uvindex  = "not found";
}
// print_r($data);
// foreach ($data as $Key => $value) {

// }

echo "</pre>";
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather Info</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="../../../public/style.css">
</head>

<body>
    <?php require_once(APP_PATH . "/views/weather/button.phtml") ?>


    <div class="h1 text-center text-danger" style="font-family: sans-serif;">Weather Forcast</div>

    <div class="mt-5"></div>
    <div style="display:inline-block; margin-left:35%; " class="">
        <?php echo $htm ?>
    </div>
</body>

</html>