<?php
// print_r($this->request->getPost());

// echo "<pre>";
// print_r($data);
$htm = "";
if (isset($data)) {

    foreach ($data as $key => $value) {
        $cityname=urlencode($value->name);
        $countryname=urlencode($value->country);
        $htm .= "        
            <tr>
            <td><a target='_blank' style='text-decoration:none; color:green' href='http://localhost:8080/weather/singlepage?place=$cityname'>$value->name</a></td>
            <td><a target='_blank' style='text-decoration:none; color:green' href='http://localhost:8080/weather/singlepage?place=$countryname'>$value->country</a></td>
            </tr>
            ";
    }
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <!-- <div class="text-center h1"></div> -->
    <nav class="navbar d-flex justify-content-center">
        <form class="form-inline" method="post">
            <input class="form-control mr-sm-2" type="search" name="location" placeholder="Search Location" aria-label="Search">
            <input class="btn btn-outline-success my-2 my-sm-0" type="submit">
    </nav>
    <table class='table table-bordered'>
        <thead class="thead-dark">
            <tr>
                <th scope='col'>City Name</th>
                <th scope='col'>Country Name</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($htm == "") {
                echo "<td>Not Found</td><td>Not Found</td>";
            } else {
                echo $htm;
            }; ?>
        </tbody>
    </table>

</body>

</html>