<?php

echo "<pre>";

if (isset($data)) {

    $updatetime = $data->location->localtime;
    $tempcel = $data->current->temp_c;
    $country = $data->location->country;
    $city = $data->location->name;
    $wind = $data->current->wind_kph;
    $pressure = $data->current->pressure_mb;
    $humidity = $data->current->humidity;
    $uvindex = $data->current->uv;
} else {

    $updatetime = "not found";
    $tempcel  = "not found";
    $country  = "not found";
    $city     = "not found";
    $wind     = "not found";
    $pressure = "not found";
    $humidity = "not found";
    $uvindex  = "not found";
}
// print_r($data);
// foreach ($data as $Key => $value) {

// }

echo "</pre>";
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather Info</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="../../../public/style.css">
</head>

<body>
    <div class="h1 text-center text-danger" style="font-family: sans-serif;">Weather Inforamtion Page</div>

    <div class="mt-5"></div>

    <div class="courses-container d-flex justify-content-center">
        <div class="course">
            <div class="course-preview">
                <div class="h6">Current Temp</div>
                <h6 class="text-info"><?php echo $tempcel ?>°C</h6>
                <h2><?php echo $city ?></h2>
                <div class="text-danger mt-2 h6"><?php echo $country ?></div>
                <div class="h6 mt-5 text-left text-info">UV Index <?php echo $uvindex ?></div>
            </div>
            <div class="course-info">
                <div class="progress-container">
                    <div class="progress"></div>
                    <span class="progress-text">
                        6/9 Challenges
                    </span>
                </div>
                <h6 class="text-danger"><b>Updated Time</b></h6>
                <h6 class="text-success"><?php echo $updatetime ?></h6>

                <h6 class="text-danger mt-4"><b>Wind Speed</b></h6>
                <h6 class="text-info"><?php echo $wind ?>kmp</h6>

                <h6 class="text-danger mt-4"><b>Pressure</b></h6>
                <h6 class="text-dark"><?php echo $wind ?>mb</h6>

                <h6 class="text-danger mt-4"><b>Humidity</b></h6>
                <h6 class="text-primary"><?php echo $humidity ?>%</h6>

                <button class="btnn"><a style="text-decoration:none; color:white" target='_blank' href="http://localhost:8080/weather/home">Home</a></button>
            </div>
        </div>
    </div>
        <?php require_once(APP_PATH."/views/weather/button.phtml")?>

</body>

</html>